import requests

LOGIN_URL = "https://account.nicovideo.jp/api/v1/login"
SETTINGS_URL = "https://www.nicovideo.jp/api/v1/user.settings.update"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

def save_cookies_to_netscape_format(cookies, filename):
    """Cookies を Netscape フォーマットで保存"""
    with open(filename, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by login.py\n")
        for cookie in cookies:
            f.write(
                f"{cookie.domain}\t"
                f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
                f"{cookie.path}\t"
                f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                f"{cookie.expires or 0}\t"
                f"{cookie.name}\t"
                f"{cookie.value}\n"
            )
    print(f"Cookies saved in Netscape format to {filename}")


def login(email, password):
    session = requests.Session()

    # ログインリクエスト
    payload = {
        "mail_tel": email,
        "password": password
    }
    response = session.post(LOGIN_URL, headers=HEADERS, data=payload)

    if response.status_code == 200 and "nicosid" in session.cookies:
        print("Login successful")

        # R-18コンテンツを有効化
        enable_r18_content(session)

        # クッキーを保存
        save_cookies_to_netscape_format(session.cookies, "cookies.txt")
    else:
        print(f"Login failed: {response.status_code} {response.text}")
        exit(1)


def enable_r18_content(session):
    """アカウントでR-18コンテンツを有効化する"""
    settings_payload = {
        "r18_enabled": "true"  # R-18コンテンツを表示する設定
    }
    response = session.post(SETTINGS_URL, headers=HEADERS, data=settings_payload, cookies=session.cookies)

    if response.status_code == 200:
        print("R-18 content enabled in account settings")
    else:
        print(f"Failed to enable R-18 content: {response.status_code} {response.text}")
        exit(1)


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 3:
        print("Usage: python3 login.py <email> <password>")
        exit(1)
    email = sys.argv[1]
    password = sys.argv[2]
    login(email, password)
