name: shikushiku Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Video URL (e.g., https://www.example.com/video/12345)"
        required: true

jobs:
  fetch_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # 必要なツールをインストール
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl ffmpeg jq

          # Pythonライブラリをインストール
          pip3 install requests

          # yt-dlp をインストール
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Fetch Cookies
        run: |
          # Cookieを取得してcookie.txtに保存
          curl -c cookies.txt -L "${{ github.event.inputs.video_url }}"

      - name: Download Video
        run: |
          video_url="${{ github.event.inputs.video_url }}"
          mkdir -p downloads
          yt-dlp "${video_url}" --cookies cookies.txt -o "downloads/%(id)s.%(ext)s"

      - name: Upload Video to Repository
        run: |
          video_url="${{ github.event.inputs.video_url }}"
          video_id=$(basename "${video_url}")
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # ダウンロードした動画をコミットしてプッシュ
          git add "downloads/${video_id}.*"
          git commit -m "Add downloaded video: ${video_id}"
          git push
