name: shikushiku downloader

on:
  workflow_dispatch:
    inputs:
      email:
        description: "NicoNico Gmail Address"
        required: true
      password:
        description: "NicoNico Account Password"
        required: true
        type: password
      video_id:
        description: "NicoNico Video ID (e.g., sm9)"
        required: true

jobs:
  fetch_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl ffmpeg jq unzip chromium-browser

          # Pythonライブラリをインストール
          pip3 install selenium requests

          # Chromedriverをダウンロードしてセットアップ
          curl -sSL https://chromedriver.storage.googleapis.com/$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # yt-dlp をインストール
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Run Selenium Login Script
        run: |
          python3 login.py "${{ github.event.inputs.email }}" "${{ github.event.inputs.password }}"

      - name: Download Video
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          mkdir -p downloads
          yt-dlp "https://www.nicovideo.jp/watch/${video_id}" --cookies cookies.txt -o "downloads/${video_id}.mp4"

      - name: Upload Video to Repository
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          git add "downloads/${video_id}.mp4"
          git commit -m "Add downloaded video: ${video_id}"
          git push
