name: Download NicoNico Video

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'NicoNico Video ID (e.g., sm1536)'
        required: true

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yt-dlp

      - name: Retrieve cookies
        run: |
          curl -c cookies.txt https://www.nicovideo.jp/

      - name: Download NicoNico Video
        id: download
        run: |
          mkdir -p downloads
          video_id="${{ github.event.inputs.video_id }}"
          yt-dlp "https://www.nicovideo.jp/watch/${video_id}" --cookies cookies.txt -o "downloads/%(title)s.%(ext)s"

      - name: Add success message to README.md
        run: |
          if [ ! -f README.md ]; then
            echo "# NicoNico Video Downloads" > README.md
            echo "このリポジトリにはニコニコ動画からダウンロードした動画が含まれます。" >> README.md
            echo "" >> README.md
          fi
          echo "✅ 成功したじょ〜☆彡: ${{ github.event.inputs.video_id }}" >> README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md downloads/
          git commit -m "Add success message and video for ${{ github.event.inputs.video_id }}"
          git push
