name: shikushiku downloader

on:
  workflow_dispatch:
    inputs:
      email:
        description: "NicoNico Gmail Address"
        required: true
      password:
        description: "NicoNico Account Password"
        required: true
        type: password
      video_id:
        description: "NicoNico Video ID (e.g., sm9)"
        required: true

jobs:
  fetch_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure .gitignore for cookies.txt
        run: |
          echo "cookies.txt" >> .gitignore
          git add .gitignore
          git commit -m "Add cookies.txt to .gitignore"

      - name: Install Dependencies
        run: |
          # 必要なツールをインストール
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl ffmpeg jq

          # Pythonライブラリをインストール
          pip3 install requests

          # yt-dlp をインストール
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Login and Save Cookies
        run: |
          email="${{ github.event.inputs.email }}"
          password="${{ github.event.inputs.password }}"

          # ログインスクリプトを作成
          cat <<EOF > login.py
import requests

LOGIN_URL = "https://account.nicovideo.jp/api/v1/login"
SETTINGS_URL = "https://www.nicovideo.jp/api/v1/user.settings.update"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

def login_and_set_preferences(email, password):
    session = requests.Session()

    # ログインリクエスト
    payload = {
        "mail_tel": email,
        "password": password
    }
    response = session.post(LOGIN_URL, headers=HEADERS, data=payload)

    if response.status_code == 200 and "nicosid" in session.cookies:
        print("Login successful")

        # 卑猥な動画（R-18）を表示する設定を有効化
        settings_payload = {
            "r18_enabled": "true"  # 設定変更: R-18動画を有効化
        }
        settings_response = session.post(SETTINGS_URL, headers=HEADERS, data=settings_payload, cookies=session.cookies)

        if settings_response.status_code == 200:
            print("Account settings updated: R-18 videos enabled")

        # クッキーを保存
        with open("cookies.txt", "w") as f:
            for key, value in session.cookies.items():
                f.write(f"{key}\t{value}\n")
        print("Cookies saved to cookies.txt")
    else:
        print("Login failed")
        exit(1)

if __name__ == "__main__":
    import sys
    email = sys.argv[1]
    password = sys.argv[2]
    login_and_set_preferences(email, password)
EOF

          # ログインスクリプトを実行
          python3 login.py "$email" "$password"

      - name: Download Video
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          mkdir -p downloads
          yt-dlp "https://www.nicovideo.jp/watch/${video_id}" --cookies cookies.txt -o "downloads/${video_id}.mp4"

      - name: Upload Video to Repository
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # ダウンロードした動画をコミットしてプッシュ
          git add "downloads/${video_id}.mp4"
          git commit -m "Add downloaded video: ${video_id}"
          git push
