name: shikushiku Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Video URL to download"
        required: true

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp requests

      - name: Download Video
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
        run: |
          mkdir -p downloads
          
          # Advanced download with multiple fallback options
          yt-dlp "$VIDEO_URL" \
            --no-warnings \
            --ignore-errors \
            --no-overwrites \
            --add-metadata \
            -f "best[ext=mp4]/best" \
            -o "downloads/%(title)s-%(id)s.%(ext)s"

      - name: List Downloaded Files
        run: |
          echo "Downloaded files:"
          ls -l downloads/
          echo "File details:"
          file downloads/*

      - name: Check File Size
        run: |
          total_size=$(du -sh downloads | cut -f1)
          echo "Total download size: $total_size"
          
          # Optional: Limit file size
          if [[ $(find downloads -type f -size +1G | wc -l) -gt 0 ]]; then
            echo "Warning: Large files detected"
          fi

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add downloads/
          git commit -m "Download video from ${{ github.event.inputs.video_url }}" || exit 0
          git push

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-video
          path: downloads/
          retention-days: 5
