name: Fetch NicoNico Comments and Download Video

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: "NicoNico Video ID (e.g., sm9)"
        required: true

jobs:
  fetch_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          # 必要なツールをインストール
          sudo apt-get update
          sudo apt-get install -y curl ffmpeg fonts-migmix jq
          
          # yt-dlp をインストール
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          
          # Deno をインストール
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "export PATH=$HOME/.deno/bin:\$PATH" >> $GITHUB_ENV

      - name: Fetch Comments
        run: |
          # GitHub Actions の inputs から動画IDを取得
          video_id="${{ github.event.inputs.video_id }}"
          mkdir -p downloads

          # Deno を使ってコメントを取得
          deno run --allow-net --allow-read --allow-write scripts/fetchComments.ts "$video_id" > "downloads/${video_id}_comments.txt"

      - name: Download Video
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          yt-dlp "https://www.nicovideo.jp/watch/${video_id}" --cookies cookies.txt -o "downloads/${video_id}.mp4"

      - name: Generate ASS Subtitles
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          comments_file="downloads/${video_id}_comments.txt"
          ass_file="downloads/${video_id}_comments.ass"
          font_path="/usr/share/fonts/opentype/migmix/migmix-1p-regular.ttf"

          # ASSファイルのヘッダーを作成
          echo "[Script Info]" > "$ass_file"
          echo "Title: NicoNico Comments" >> "$ass_file"
          echo "ScriptType: v4.00+" >> "$ass_file"
          echo "Collisions: Normal" >> "$ass_file"
          echo "" >> "$ass_file"
          echo "[V4+ Styles]" >> "$ass_file"
          echo "Style: Default,Migu 1P,24,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1" >> "$ass_file"
          echo "" >> "$ass_file"
          echo "[Events]" >> "$ass_file"

          # コメントを読み込んでASSファイルに追加
          while read -r line; do
            time=$(echo "$line" | awk '{print $1}')
            comment=$(echo "$line" | cut -f2-)
            start_time=$time
            end_time=$(date -d@$(( $(date -d"$time" +%s) + 4 )) -u +%H:%M:%S)
            echo "Dialogue: 0,$start_time,$end_time,Default,,0,0,0,,{\move(1280,0,-200,0)}$comment" >> "$ass_file"
          done < "$comments_file"

      - name: Overlay Comments on Video
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          ffmpeg -i "downloads/${video_id}.mp4" -vf "ass=downloads/${video_id}_comments.ass" -c:v libx264 -c:a copy "downloads/${video_id}_with_comments.mp4"
