name: Download NicoNico Video with Comments

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'NicoNico Video ID (e.g., sm9)'
        required: true

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip curl ffmpeg fonts-migmix jq
          pip3 install requests beautifulsoup4

      - name: Run cm.py to fetch comments
        id: fetch_comments
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          mkdir -p downloads
          python3 scripts/cm.py "$video_id" > "downloads/${video_id}_comments.txt"

      - name: Generate ASS Subtitle for NicoNico Style Comments
        id: generate_ass
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          comments_txt="downloads/${video_id}_comments.txt"
          ass_file="downloads/comments.ass"
          font_path="/usr/share/fonts/opentype/migmix/migmix-1p-regular.ttf"

          # Create ASS subtitle header
          echo "[Script Info]" > "$ass_file"
          echo "Title: NicoNico Comments" >> "$ass_file"
          echo "ScriptType: v4.00+" >> "$ass_file"
          echo "Collisions: Normal" >> "$ass_file"
          echo "PlayDepth: 0" >> "$ass_file"
          echo "" >> "$ass_file"
          echo "[V4+ Styles]" >> "$ass_file"
          echo "Format: Name, Fontname, Fontsize, PrimaryColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding" >> "$ass_file"
          echo "Style: Default,Migu 1P,24,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,10,1" >> "$ass_file"
          echo "" >> "$ass_file"
          echo "[Events]" >> "$ass_file"
          echo "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text" >> "$ass_file"

          # Add comments to ASS file
          while read -r line; do
            # Extract time and comment from each line in the txt file
            time=$(echo "$line" | awk '{print $1}')
            comment=$(echo "$line" | cut -f2-)

            # Generate moving comments (right to left)
            start_time=$time
            end_time=$(date -d@$(( $(date -d"$time" +%s) + 4 )) -u +%H:%M:%S)
            echo "Dialogue: 0,$start_time,$end_time,Default,,0,0,0,,{\move(1280,0,-200,0)}$comment" >> "$ass_file"
          done < "$comments_txt"

      - name: Download NicoNico Video
        id: download_video
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          yt-dlp "https://www.nicovideo.jp/watch/${video_id}" \
            --cookies cookies.txt \
            -o "downloads/${video_id}.mp4" \
            --merge-output-format mp4

      - name: Overlay Comments on Video
        id: overlay_comments
        run: |
          video_id="${{ github.event.inputs.video_id }}"
          video_path="downloads/${video_id}.mp4"
          ass_file="downloads/comments.ass"
          output_path="downloads/${video_id}_with_comments.mp4"

          # Overlay comments on video using FFmpeg
          ffmpeg -i "$video_path" -vf "ass=$ass_file" -c:v libx264 -crf 23 -preset veryfast -c:a copy "$output_path"

      - name: Upload Video and Update README
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          if [ ! -f README.md ]; then
            echo "# NicoNico Video Downloads" > README.md
            echo "このリポジトリにはニコニコ動画からダウンロードした動画が含まれます。" >> README.md
            echo "" >> README.md
          fi
          echo "✅ 成功したじょ〜☆彡: ${{ github.event.inputs.video_id }}" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md downloads/
          git commit -m "Add video and comments for ${{ github.event.inputs.video_id }}"
          git push
