name: Universal Video Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "Video URL to download"
        required: true
      visitor_data:
        description: "Visitor data for specific platforms (optional)"
        required: false

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl
          pip install yt-dlp requests

      - name: Fetch Cookies
        run: |
          # Fetch cookies from the platform if necessary
          curl -c cookies.txt -L "https://www.example.com" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

      - name: Download Video
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
          VISITOR_DATA: ${{ github.event.inputs.visitor_data }}
        run: |
          mkdir -p downloads
          
          # Check if the URL is from YouTube
          if [[ "$VIDEO_URL" == *"youtube.com"* || "$VIDEO_URL" == *"youtu.be"* ]]; then
            # Download video from YouTube, skipping webpage request
            yt-dlp "$VIDEO_URL" \
              --no-warnings \
              --ignore-errors \
              --no-overwrites \
              --add-metadata \
              --extractor-args "youtubetab:skip=webpage" \
              --extractor-args "youtube:player_skip=webpage,configs;visitor_data=${VISITOR_DATA}" \
              --cookies cookies.txt \
              -f "best[ext=mp4]/best" \
              -o "downloads/%(title)s-%(id)s.%(ext)s"
          else
            # Download video from other platforms
            yt-dlp "$VIDEO_URL" \
              --no-warnings \
              --ignore-errors \
              --no-overwrites \
              --add-metadata \
              --cookies cookies.txt \
              -f "best[ext=mp4]/best" \
              -o "downloads/%(title)s-%(id)s.%(ext)s" \
              ${VISITOR_DATA:+--extractor-args "visitor_data=${VISITOR_DATA}"}
          fi

      - name: List Downloaded Files
        run: |
          echo "Downloaded files:"
          ls -l downloads/
          echo "File details:"
          file downloads/*

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add downloads/
          git commit -m "Download video from ${{ github.event.inputs.video_url }}" || exit 0
          git push

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-video
          path: downloads/
          retention-days: 5
